server:
  port: 8089

initializr:
  group-id:
    value: in.zeta
  artifact-id:
    value: zeta-app
  dependencies:
    - name: Web
      content:
        - name: Web
          id: web
          description: Build web, including RESTful, applications using Spring MVC. Uses Apache Tomcat as the default embedded container.
    - name: Zeta-Delta
      content:
        - name: Zeta-Delta
          id: zeta-delta
          groupId: in.zeta
          artifactId: delta-library
          version: 2.1.12
          description: Zeta Delta Library
    - name: Zeta-Crux
      content:
        - name: Zeta-Crux
          id: zeta-crux
          groupId: in.zeta
          artifactId: crux
          version: 2.3.4
          description: Zeta Crux Library
  types:
    - name: Maven Project
      id: maven-project
      description: Generate a Maven based project archive
      tags:
        build: maven
        format: project
      default: true
      action: /starter.zip
    - name: Gradle Project
      id: gradle-project
      description: Generate a Gradle based project archive
      tags:
        build: gradle
        format: project
      default: false
      action: /starter.zip
  packagings:
    - name: Jar
      id: jar
      default: true
  javaVersions:
    - id: 11
      default: false
    - id: 1.8
      name: 8
      default: true
  languages:
    - name: Java
      id: java
      default: true
    - name: Kotlin
      id: kotlin
      default: false
    - name: Groovy
      id: groovy
      default: false
  bootVersions:
    - id: 2.4.0-SNAPSHOT
      name: 2.4.0 (SNAPSHOT)
      default: false
    - id: 2.3.3.BUILD-SNAPSHOT
      name: 2.3.3 (SNAPSHOT)
      default: false
    - id: 2.3.2.RELEASE
      name: 2.3.2
      default: true