pipeline {
  agent any
  triggers {
     pollSCM '* * * * *'

  }
  stages {
    stage('Build') {
       steps{
          mvn clean -U package
        }
    }
    stage('Deploy') {
        steps{
           mvn spring-boot:run
        }
    }
  }
}